# markdown
markdown: kramdown
kramdown:
  extensions: ["superscript","tables","with_toc_data","strikethrough","smart"]
highlighter: rouge

plugins:
  - jemoji
  - jekyll-redirect-from

exclude:
- ".ruby-version"
- ".jekyll-metadata"
- ".gitignore"
- ".travis.yml"
- todo.txt
- resources
- Gemfile
- Gemfile.lock
- Makefile
- vendor
- README.md
- CONTRIBUTING.md
- LICENSE.md

# Site metadata
name: "Emerging Citizen Technology"
description: "Just a fraction of federal emerging citizen technology."
baseurl: ""

# Google Analytics
google_analytics: UAâ€”110413123-1

# Uncomment the following line for localhost development at http://127.0.0.1:4000/software/
# baseurl: /software

# GitHub information
org_name: gsa
repo_name: emerging-technology-atlas
branch: master

# Navigation
# List links that should appear in the site sidebar here
navigation:
- text: "Home"
  url: /
- text: "About Us"
  sub_nav:
  - text: "What We Do"
    url: /what-we-do/
  - text: "Participating Agencies"
    url: /participating-agencies/
  - text: "Connect"
    url: /connect/
  - text: "Contribute"
    url: /howto/
  - text: "Meeting Notes & Action Items"
    url: /meeting-notes/
- text: "Emerging Technologies for Government Services"
  url: /emerging-tech-gov-services/
- text: "Our Interagency Initiatives"
  url: /interagency-initiatives/
